import React, { useState, useEffect, useMemo } from 'react';
import { CheckCircle, Copy, RefreshCw, Trash2, ChevronRight, Send, Mail, MessageSquare, Instagram, Facebook, Megaphone, FileText } from 'lucide-react';
import { API_URL } from '../../config';

const STATUS_COLORS = {
  PENDING_REVIEW: { bg:'bg-yellow-500/20', text:'text-yellow-400', label:'To Review' },
  APPROVED: { bg:'bg-green-500/20', text:'text-green-400', label:'Sent / Ready' },
  NEEDS_EDIT: { bg:'bg-orange-500/20', text:'text-orange-400', label:'Needs Edit' },
  REJECTED: { bg:'bg-red-500/20', text:'text-red-400', label:'Discarded' }
};
const CHANNEL_META = {
  email:{icon:Mail,label:'Email',color:'text-blue-400'}, sms:{icon:MessageSquare,label:'SMS',color:'text-green-400'}, instagram:{icon:Instagram,label:'Instagram DM',color:'text-pink-400'}, facebook:{icon:Facebook,label:'Facebook DM',color:'text-blue-500'}, whatsapp:{icon:MessageSquare,label:'WhatsApp',color:'text-emerald-400'}, ghl:{icon:Send,label:'GHL',color:'text-purple-400'}, content:{icon:Megaphone,label:'Content',color:'text-cyan-400'}
};
function parseMeta(raw){ try{return typeof raw==='string'?JSON.parse(raw):(raw||null);}catch{return null;} }
function isAffiliateDraft(draft){ const meta=parseMeta(draft.pipeline_metadata); return meta?.kind==='affiliate_message'||meta?.kind==='content'||meta?.affiliateId||meta?.affiliateName||draft.created_by==='affiliate-hub'; }
function channelOf(draft){ const meta=parseMeta(draft.pipeline_metadata); if(meta?.channel&&CHANNEL_META[meta.channel])return meta.channel; if(meta?.kind==='content')return 'content'; return 'ghl'; }

export default function OutboundQueue({isDark=true,onReuse}){
  const [drafts,setDrafts]=useState([]),[stats,setStats]=useState({}),[loading,setLoading]=useState(false),[filter,setFilter]=useState('PENDING_REVIEW'),[kindFilter,setKindFilter]=useState('all'),[expanded,setExpanded]=useState(null),[collapsed,setCollapsed]=useState(false);
  const fetchDrafts=async()=>{setLoading(true);try{const[dRes,sRes]=await Promise.all([fetch(`${API_URL}/api/drafts?status=${filter}&limit=100`),fetch(`${API_URL}/api/drafts/stats`)]);if(dRes.ok)setDrafts(((await dRes.json()).drafts||[]).filter(isAffiliateDraft));if(sRes.ok)setStats(await sRes.json());}catch(e){console.error('Failed to fetch affiliate outbound queue:',e);}finally{setLoading(false);}};
  useEffect(()=>{fetchDrafts();},[filter]); useEffect(()=>{const t=setInterval(fetchDrafts,30000);return()=>clearInterval(t);},[filter]);
  const updateStatus=async(id,status)=>{try{await fetch(`${API_URL}/api/drafts/${id}/status`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});fetchDrafts();}catch(e){console.error(e);}};
  const remove=async id=>{try{await fetch(`${API_URL}/api/drafts/${id}`,{method:'DELETE'});fetchDrafts();}catch{}};
  const copy=text=>navigator.clipboard.writeText(text).catch(()=>{});
  const visible=useMemo(()=>drafts.filter(d=>{if(kindFilter==='all')return true;const ch=channelOf(d);return kindFilter==='content'?ch==='content':ch!=='content';}),[drafts,kindFilter]);
  const pendingCount=drafts.filter(d=>d.status==='PENDING_REVIEW').length;
  return <div className={`overflow-hidden rounded-xl ${isDark?'bg-[#080d12] border border-cyan-500/15 shadow-inner shadow-black/20':'bg-white border border-gray-200'}`}>
    <button onClick={()=>setCollapsed(!collapsed)} className={`w-full p-4 flex items-center justify-between ${collapsed?'':'border-b'} ${isDark?'border-purple-900/20':'border-gray-100'}`}><div className="flex items-center gap-3"><Send className="w-4 h-4 text-purple-400"/><h3 className={`text-sm font-bold ${isDark?'text-white':'text-gray-900'}`}>Affiliate Outbound Queue</h3>{pendingCount>0&&<span className="px-2 py-0.5 rounded-full bg-yellow-500/20 text-yellow-400 text-xs font-medium">{pendingCount} to review</span>}<span className={`text-xs ${isDark?'text-gray-500':'text-gray-400'}`}>affiliate messages & content only</span></div><ChevronRight className={`w-4 h-4 transition-transform ${collapsed?'':'rotate-90'} ${isDark?'text-gray-400':'text-gray-500'}`}/></button>
    {!collapsed&&<><div className="px-4 pt-3 flex flex-wrap items-center gap-1">{['PENDING_REVIEW','APPROVED','NEEDS_EDIT','REJECTED'].map(status=><button key={status} onClick={()=>setFilter(status)} className={`px-2.5 py-1 text-xs rounded-lg ${filter===status?`${STATUS_COLORS[status].bg} ${STATUS_COLORS[status].text}`:isDark?'text-gray-500 hover:bg-white/5':'text-gray-400'}`}>{STATUS_COLORS[status].label}</button>)}<div className="ml-auto flex items-center gap-1">{['all','message','content'].map(k=><button key={k} onClick={()=>setKindFilter(k)} className={`px-2 py-1 text-xs rounded-lg capitalize ${kindFilter===k?'bg-purple-600/30 text-purple-300':'text-gray-500 hover:bg-white/5'}`}>{k==='message'?'Messages':k}</button>)}<button onClick={fetchDrafts} className="p-1.5 rounded hover:bg-white/10"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''} text-gray-400`}/></button></div></div>
    <div className="max-h-80 overflow-y-auto mt-2">{visible.length===0?<div className="p-6 text-center text-gray-600"><Send className="w-6 h-6 mx-auto mb-2 opacity-50"/><p className="text-sm">No affiliate outbound items in this status. Old support-ticket drafts are intentionally hidden from this AFM workspace.</p></div>:visible.map(draft=>{const ch=channelOf(draft),CM=CHANNEL_META[ch],ChIcon=CM.icon,isOpen=expanded===draft.id,style=STATUS_COLORS[draft.status]||STATUS_COLORS.PENDING_REVIEW,meta=parseMeta(draft.pipeline_metadata);return <div key={draft.id} className="border-b last:border-b-0 border-purple-900/10"><div className="px-4 py-3 flex items-center gap-3 cursor-pointer hover:bg-white/5" onClick={()=>setExpanded(isOpen?null:draft.id)}><ChevronRight className={`w-4 h-4 transition-transform ${isOpen?'rotate-90':''} text-gray-500`}/><span className={`flex items-center gap-1 px-2 py-0.5 rounded text-xs bg-white/5 ${CM.color}`}><ChIcon className="w-3 h-3"/>{CM.label}</span><div className="flex-1 min-w-0"><div className="text-sm font-medium truncate text-white">{draft.ticket_subject||'Untitled'}</div><div className="text-xs mt-0.5 text-gray-500">{meta?.affiliateName?`${meta.affiliateName} · `:''}{new Date(draft.created_at).toLocaleString()}</div></div><span className={`px-2 py-0.5 rounded text-xs ${style.bg} ${style.text}`}>{style.label}</span></div>{isOpen&&<div className="px-4 pb-4 bg-white/[0.02]"><div className="p-3 rounded-lg text-sm whitespace-pre-wrap mb-3 max-h-48 overflow-y-auto bg-white/5 text-gray-300">{draft.draft_text}</div><div className="flex flex-wrap gap-2">{draft.status!=='APPROVED'&&<button onClick={()=>updateStatus(draft.id,'APPROVED')} className="flex items-center gap-1 px-3 py-1.5 text-xs rounded-lg bg-green-600 text-white"><CheckCircle className="w-3 h-3"/>Mark Sent</button>}{draft.status!=='NEEDS_EDIT'&&<button onClick={()=>updateStatus(draft.id,'NEEDS_EDIT')} className="flex items-center gap-1 px-3 py-1.5 text-xs rounded-lg bg-orange-600/20 text-orange-400"><FileText className="w-3 h-3"/>Needs Edit</button>}<button onClick={()=>copy(draft.draft_text)} className="flex items-center gap-1 px-3 py-1.5 text-xs rounded-lg bg-white/10 text-white"><Copy className="w-3 h-3"/>Copy</button>{onReuse&&<button onClick={()=>onReuse(draft)} className="flex items-center gap-1 px-3 py-1.5 text-xs rounded-lg bg-purple-600/20 text-purple-300"><Send className="w-3 h-3"/>Open in Composer</button>}<button onClick={()=>remove(draft.id)} className="flex items-center gap-1 px-3 py-1.5 text-xs rounded-lg bg-red-600/10 text-red-400 ml-auto"><Trash2 className="w-3 h-3"/></button></div></div>}</div>;})}</div></>}
  </div>;
}
