import React, { useMemo, useState } from 'react';
import { Activity, AlertTriangle, ArrowUpRight, BarChart3, CheckCircle2, Clock3, MessageSquare, RefreshCw, Shield, Sparkles, Target, Trophy, Search } from 'lucide-react';

const priorities = [
  {priority:1,motion:'Reactivate',affiliate:'David Summer',why:'124 previous-quarter trials → 0 current-quarter trials in the earlier book snapshot; largest recoverable volume signal in that source.',outcome:'Diagnose the decline and agree on one restart campaign.',success:'Reply + dated promotion plan + new trial activity.',timing:'Today',tone:'rose'},
  {priority:2,motion:'Reactivate',affiliate:'James Hurst',why:'985 lifetime trials in the earlier book snapshot; only 15 from the 1,000-trial milestone.',outcome:'Secure one milestone campaign tied to his existing audience.',success:'Campaign commitment + 15 incremental trials.',timing:'Today',tone:'amber'},
  {priority:3,motion:'Protect',affiliate:'Big Bear Digital',why:'697 lifetime trials but only 1 current-quarter trial in the earlier book snapshot; source marks Needs Attention.',outcome:'Identify the cause of decline and protect a historically valuable relationship.',success:'Two-way conversation + one agreed recovery action.',timing:'Today',tone:'amber'},
  {priority:4,motion:'Reactivate',affiliate:'Corda Systems',why:'262 lifetime trials; engaged record; 2 previous-quarter trials and 0 current-quarter trials in the earlier book snapshot.',outcome:'Surface the blocker and select a low-effort reactivation play.',success:'Blocker classified + next action dated.',timing:'Today',tone:'rose'},
  {priority:5,motion:'Reactivate',affiliate:'Abigail Ogbe',why:'188 lifetime trials; transferred partner; public channels exist; current activity was quiet in the earlier book snapshot.',outcome:'Open the relationship and secure a repeatable content or promo test.',success:'Reply + dated content/promo commitment.',timing:'Today',tone:'rose'},
  {priority:6,motion:'Grow',affiliate:'Khawajamuntazir22',why:'Sep 23 attribution report: 4 MTD trials; weekly movement accelerated from 1 trial (Sep 7–13) to 3 trials (Sep 14–20); lifetime trial rank moved 130 → 133.',outcome:'Identify what generated the recent traction and schedule a repeatable promotion while momentum is fresh.',success:'Documented channel/offer + next dated promotion.',timing:'Today',tone:'emerald'},
  {priority:7,motion:'Grow',affiliate:'Jono Catliff',why:'311 lifetime trials, 3 current-quarter trials, AI-automation audience and known public channels in the earlier book snapshot.',outcome:'Turn audience insight into one relevant HighLevel content test.',success:'Topic selected + publish date agreed.',timing:'2 business days',tone:'emerald'},
  {priority:8,motion:'Grow',affiliate:'Inspired Johann',why:'Sep 23 attribution report: 1 MTD trial, generated during Sep 14–20; lifetime trial rank is 108.',outcome:'Find the source of the recent trial and determine whether the motion can repeat.',success:'Acquisition source identified + one repeat action dated.',timing:'2 business days',tone:'emerald'},
  {priority:9,motion:'Grow',affiliate:'Ahmmad',why:'Sep 23 attribution report: 1 MTD trial in the current week (Sep 21–27); lifetime trial rank is 104.',outcome:'Capture what triggered the new activity and reinforce it quickly.',success:'Current source confirmed + next action dated.',timing:'2 business days',tone:'cyan'},
];

const signals = [
  {label:'Book size',value:'51',detail:'earlier assigned-book snapshot',icon:Target},
  {label:'Prior full-book MTD',value:'131',detail:'older broad portfolio snapshot · stale/pending refresh',icon:Activity},
  {label:'Sep 23 attributed MTD',value:'6',detail:'narrow post-100 activity report only',icon:BarChart3},
  {label:'Named producers',value:'3',detail:'current-month activity in Sep 23 extract',icon:Trophy},
  {label:'Subset month pace',value:'≈8',detail:'6 / 23 × 30 · calculated, not a full-book forecast',icon:ArrowUpRight},
  {label:'Commit vs pace',value:'Pending',detail:'needs current full-book target + comparable source',icon:Clock3},
  {label:'CQ trials',value:'20',detail:'earlier book snapshot · period may be incomplete',icon:MessageSquare},
  {label:'Reactivation',value:'16',detail:'earlier working-status queue',icon:RefreshCw},
];

const attributionPulse = [
  {affiliate:'Khawajamuntazir22',mtd:4,recent:'1 trial Sep 7–13 → 3 trials Sep 14–20',rank:'130 → 133',status:'Accelerating'},
  {affiliate:'Inspired Johann',mtd:1,recent:'1 trial Sep 14–20',rank:'108',status:'Active · low velocity'},
  {affiliate:'Ahmmad',mtd:1,recent:'1 trial Sep 21–27',rank:'104',status:'New current-week activity'},
];

const benchmark = [
 ['Alisha Tran',4,24553,1],['Andrew Mason',11,4625,2],['Kara Rhoads',42,3849,3],['Melissa Soza',37,3345,4],['Matthew Martinez',34,3067,5],['Danica Deaton',29,2657,6],['Angela Mason',41,2285,7],['Taylor DeBaylo',13,1357,8],['Jade Barbosa',35,1117,9],['Amanda Webster',26,469,11],['Jamaur Johnson',51,20,17]
];

const profiles = [
  ['James Hurst','GoHighLevel ecosystem educator','YouTube','1,000-trial milestone'],
  ['Abigail Ogbe','Functional medicine clinics','Public social','Audience-specific relaunch'],
  ['Dannymenake28','AI outbound / B2B lead generation','YouTube + Community','Workflow/content fit'],
  ['Jono Catliff','AI automation educator','YouTube + Community','HighLevel workflow tutorial'],
  ['Hoang Nguyen','Build-in-public entrepreneurship','Instagram + YouTube','Hold / do-not-contact'],
  ['Dom Bavaro','HighLevel education for creators/agencies','YouTube + TikTok','Content intelligence'],
];

const toneClass = {rose:'border-rose-400/20 bg-rose-500/[.06] text-rose-200',amber:'border-amber-400/20 bg-amber-500/[.06] text-amber-200',emerald:'border-emerald-400/20 bg-emerald-500/[.06] text-emerald-200',cyan:'border-cyan-400/20 bg-cyan-500/[.06] text-cyan-200'};

export default function PortfolioIntelligence(){
 const [view,setView]=useState('brief');
 const [selected,setSelected]=useState(priorities[0]);
 const todayCount=useMemo(()=>priorities.filter(x=>x.timing==='Today').length,[]);
 return <section className="space-y-4">
  <div className="rounded-2xl border border-emerald-400/20 bg-gradient-to-br from-[#07100c] via-[#080d0c] to-[#070b0d] p-5">
   <div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><div><div className="flex items-center gap-2 text-xs uppercase tracking-[.18em] text-emerald-300"><Sparkles className="h-4 w-4"/>Portfolio intelligence v1</div><h3 className="mt-2 text-xl font-bold text-white">Action-First Affiliate Portfolio</h3><p className="mt-1 max-w-3xl text-sm text-slate-400">Transforms the September portfolio workbook into an operating layer: signal → priority → outreach → outcome → measured reactivation.</p></div><div className="rounded-xl border border-emerald-400/20 bg-emerald-400/[.06] px-4 py-3"><div className="text-[10px] uppercase tracking-wider text-emerald-300">Today</div><div className="mt-1 text-2xl font-bold text-white">{todayCount}</div><div className="text-xs text-slate-500">priority actions</div></div></div>
   <div className="mt-5 flex flex-wrap gap-2">{[['brief','Executive Brief'],['queue','Outreach Queue'],['profiles','Profile Intelligence'],['benchmark','Benchmark']].map(([id,label])=><button key={id} onClick={()=>setView(id)} className={`rounded-lg border px-3 py-2 text-xs font-semibold ${view===id?'border-emerald-400/30 bg-emerald-400/10 text-emerald-200':'border-white/10 text-slate-500 hover:text-white'}`}>{label}</button>)}</div>
  </div>
  {view==='brief'&&<><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{signals.map(({label,value,detail,icon:Icon})=><div key={label} className="rounded-xl border border-white/10 bg-white/[.025] p-4"><Icon className="h-4 w-4 text-emerald-300"/><div className="mt-2 text-2xl font-bold text-white">{value}</div><div className="text-xs font-semibold text-slate-300">{label}</div><div className="mt-1 text-[11px] text-slate-600">{detail}</div></div>)}</div><div className="grid gap-3 xl:grid-cols-4"><Signal icon={AlertTriangle} title="Biggest risk" name="David Summer" body="124 PQ → 0 CQ. Diagnose traffic, offer, tracking or operational blockers before prescribing a campaign."/><Signal icon={Target} title="Milestone play" name="James Hurst" body="985 lifetime trials. Only 15 trials from the 1,000-trial milestone."/><Signal icon={ArrowUpRight} title="Active growth signal" name="Khawajamuntazir22" body="Fresh production + Active + Engaged. Capture what generated the motion and repeat it."/><Signal icon={Shield} title="Hold / verify" name="Hoang365Days" body="Large historical decline signal, but source explicitly marks suspension / no-contact. Do not automate outreach."/></div><div className="rounded-xl border border-amber-400/15 bg-amber-500/[.04] p-4 text-xs leading-5 text-amber-100"><b>Interpretation guard:</b> The Sep 23 report is a narrow attribution extract for producing Expand / Post-100 Credit affiliates. Its 6 MTD trials are not directly comparable to the older 131-trial full-book snapshot and must not overwrite it. Full-book commit and pace stay pending until a current comparable source/target is available. The older 20 CQ vs 254 PQ view also remains an investigation signal, not a final QoQ conclusion.</div><div className="overflow-hidden rounded-xl border border-cyan-400/15 bg-cyan-500/[.03]"><div className="border-b border-white/5 px-4 py-3"><div className="text-[10px] uppercase tracking-wider text-cyan-300">Sep 23 attribution pulse</div><div className="mt-1 text-xs text-slate-500">Current-month named movement · Expand / Post-100 Credit · source as of Sep 23</div></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-xs"><thead className="text-slate-600"><tr><th className="p-3">Affiliate</th><th>MTD</th><th>Recent movement</th><th>Lifetime trial rank</th><th>Status</th></tr></thead><tbody>{attributionPulse.map(row=><tr key={row.affiliate} className="border-t border-white/5 text-slate-300"><td className="p-3 font-semibold text-white">{row.affiliate}</td><td>{row.mtd}</td><td>{row.recent}</td><td>{row.rank}</td><td className="text-emerald-300">{row.status}</td></tr>)}</tbody></table></div></div></>}
  {view==='queue'&&<div className="grid gap-4 xl:grid-cols-[1.15fr_.85fr]"><div className="space-y-2">{priorities.map(p=><button key={p.priority} onClick={()=>setSelected(p)} className={`w-full rounded-xl border p-4 text-left transition ${selected.priority===p.priority?'border-emerald-400/30 bg-emerald-400/[.07]':'border-white/10 bg-white/[.02] hover:bg-white/[.04]'}`}><div className="flex items-start gap-3"><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg border border-white/10 bg-black/20 text-xs font-bold text-white">{p.priority}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="font-semibold text-white">{p.affiliate}</span><span className={`rounded-full border px-2 py-0.5 text-[10px] ${toneClass[p.tone]}`}>{p.motion}</span></div><div className="mt-1 text-xs leading-5 text-slate-500">{p.why}</div></div><Clock3 className="h-4 w-4 text-slate-600"/></div></button>)}</div><div className="xl:sticky xl:top-4 xl:self-start rounded-2xl border border-emerald-400/20 bg-[#07100c] p-5"><div className="text-[10px] uppercase tracking-wider text-emerald-300">Next best action</div><h4 className="mt-2 text-xl font-bold text-white">{selected.affiliate}</h4><div className="mt-1 text-sm text-slate-500">{selected.motion} · {selected.timing}</div><Detail label="Why now" value={selected.why}/><Detail label="Desired outcome" value={selected.outcome}/><Detail label="Success metric" value={selected.success}/><div className="mt-4 grid grid-cols-2 gap-2"><Action icon={Search}>Affiliate 360</Action><Action icon={MessageSquare}>Draft Outreach</Action><Action icon={CheckCircle2}>Log Touch</Action><Action icon={Clock3}>Follow-up</Action></div><div className="mt-3 text-[10px] leading-4 text-slate-600">Buttons are UI workflow targets; CRM writes should remain staff-scoped and require the live Company / My Book connection.</div></div></div>}
  {view==='profiles'&&<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{profiles.map(([name,niche,channel,opportunity])=><div key={name} className="rounded-xl border border-white/10 bg-white/[.025] p-4"><div className="font-semibold text-white">{name}</div><div className="mt-2 text-xs text-slate-500">{niche}</div><div className="mt-4 flex justify-between border-t border-white/5 pt-3 text-[11px]"><span className="text-cyan-300">{channel}</span><span className="text-emerald-300">{opportunity}</span></div></div>)}</div>}
  {view==='benchmark'&&<div className="rounded-2xl border border-white/10 bg-white/[.02] p-4"><div className="mb-4 flex items-start justify-between gap-4"><div><h4 className="font-semibold text-white">Company benchmark · read only</h4><p className="mt-1 text-xs text-slate-500">Bird's-eye comparison only. Never use this table to trigger actions on another manager's book.</p></div><BarChart3 className="h-5 w-5 text-purple-300"/></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-xs"><thead className="text-slate-600"><tr><th className="p-2">AFM</th><th>Affiliates</th><th>CQ trials</th><th>CQ rank</th></tr></thead><tbody>{benchmark.map(([name,count,cq,rank])=><tr key={name} className={`border-t border-white/5 ${name==='Jamaur Johnson'?'bg-emerald-400/[.06] text-emerald-100':'text-slate-400'}`}><td className="p-2 font-medium">{name}</td><td>{count}</td><td>{cq.toLocaleString()}</td><td>#{rank}</td></tr>)}</tbody></table></div><div className="mt-3 text-[11px] text-slate-600">Rank reflects the supplied workbook snapshot, not a judgment of manager performance. Portfolio composition and incomplete periods can materially affect comparisons.</div></div>}
 </section>
}

function Signal({icon:Icon,title,name,body}){return <div className="rounded-xl border border-white/10 bg-white/[.025] p-4"><div className="flex items-center gap-2 text-[10px] uppercase tracking-wider text-slate-500"><Icon className="h-4 w-4 text-amber-300"/>{title}</div><div className="mt-3 font-semibold text-white">{name}</div><div className="mt-1 text-xs leading-5 text-slate-500">{body}</div></div>}
function Detail({label,value}){return <div className="mt-4"><div className="text-[10px] uppercase tracking-wider text-slate-600">{label}</div><div className="mt-1 text-xs leading-5 text-slate-300">{value}</div></div>}
function Action({icon:Icon,children}){return <button className="inline-flex items-center justify-center gap-2 rounded-lg border border-white/10 bg-white/[.03] px-3 py-2 text-[11px] text-slate-300 hover:border-emerald-400/20 hover:text-white"><Icon className="h-3.5 w-3.5"/>{children}</button>}
