import React,{useEffect,useMemo,useState} from 'react';
import { AlertTriangle, Bot, ExternalLink, Film, Radio, RefreshCw, Sparkles, Users } from 'lucide-react';
import ContentEngine from './ContentEngine';

const CLIPPEDIT_URL=import.meta.env.VITE_CLIPPEDIT_URL||'https://clipped.liv8.co';
const OBS_REMOTE_URL=import.meta.env.VITE_OBS_REMOTE_URL||'https://obsremote.liv8.co';
const LOCAL_CLIPPEDIT='http://localhost:3102';
const LOCAL_OBS='http://localhost:3101';
const TABS=[['engine','Content Engine',Sparkles],['clippedit','Clipped It',Film],['obs','OBS Remote',Radio],['agents','Agent Studio',Users]];

export default function CreatorControlRoomLive(){
 const [tab,setTab]=useState('engine');
 return <div className="space-y-5"><div className="flex flex-col xl:flex-row xl:items-center justify-between gap-4"><div><div className="text-xs uppercase tracking-[.2em] text-purple-300">Creator operations</div><h1 className="text-2xl font-bold text-white">Content & Broadcast Control Room</h1><p className="text-sm text-gray-500 mt-1">Content Engine + Clippedit + OBS Remote + agent production team.</p></div><div className="flex flex-wrap gap-2">{TABS.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`px-3 py-2 rounded-lg border text-sm flex items-center gap-2 ${tab===id?'bg-purple-500/20 border-purple-400/40 text-white':'bg-white/[.03] border-white/10 text-gray-400'}`}><Icon className="w-4 h-4"/>{label}</button>)}</div></div>{tab==='engine'&&<ContentEngine/>}{tab==='clippedit'&&<RemoteApp title="Clipped It — Livestream Intelligence" publicUrl={CLIPPEDIT_URL} localUrl={LOCAL_CLIPPEDIT} description="Live radar, trending, emerging moments and rights-aware clip intelligence."/>}{tab==='obs'&&<RemoteApp title="OBS Remote — Broadcast Console" publicUrl={OBS_REMOTE_URL} localUrl={LOCAL_OBS} description="Scenes, audio, stream/record, sounds, playlists and confidence monitoring."/>}{tab==='agents'&&<AgentStudio/>}</div>
}

function RemoteApp({title,publicUrl,localUrl,description}){
 const [frameKey,setFrameKey]=useState(0),[state,setState]=useState('checking');
 useEffect(()=>{let done=false;setState('checking');const c=new AbortController();const timer=setTimeout(()=>{if(!done){c.abort();setState('unreachable')}},6000);fetch(publicUrl,{method:'GET',mode:'no-cors',signal:c.signal}).then(()=>{done=true;clearTimeout(timer);setState('online')}).catch(()=>{done=true;clearTimeout(timer);setState('unreachable')});return()=>{done=true;clearTimeout(timer);c.abort()}},[publicUrl,frameKey]);
 const localHost=typeof window!=='undefined'&&['localhost','127.0.0.1'].includes(window.location.hostname);const activeUrl=localHost&&state==='unreachable'?localUrl:publicUrl;
 return <div className="rounded-2xl border border-white/10 bg-[#090a10] overflow-hidden min-h-[760px]"><div className="px-4 py-3 border-b border-white/10 flex flex-wrap items-center justify-between gap-3"><div><div className="text-sm font-semibold text-white">{title}</div><div className="text-xs text-gray-500">{description}</div><div className={`text-[11px] mt-1 ${state==='online'?'text-emerald-300':state==='checking'?'text-amber-300':'text-red-300'}`}>{state==='online'?'Public endpoint reachable':state==='checking'?'Checking public endpoint…':`Public endpoint unavailable: ${publicUrl}`}{localHost&&state==='unreachable'?' · using local fallback':''}</div></div><div className="flex gap-2"><button onClick={()=>setFrameKey(x=>x+1)} className="px-3 py-2 text-xs rounded-lg bg-white/5 text-gray-300"><RefreshCw className="w-3.5 h-3.5 inline mr-1"/>Reload</button><button onClick={()=>window.open(activeUrl,'_blank','noopener,noreferrer')} className="px-3 py-2 text-xs rounded-lg bg-purple-500/15 border border-purple-500/25 text-purple-200"><ExternalLink className="w-3.5 h-3.5 inline mr-1"/>Open full app</button></div></div>{state==='unreachable'&&!localHost&&<div className="m-4 rounded-xl border border-red-500/25 bg-red-500/10 p-3 text-sm text-red-300"><AlertTriangle className="w-4 h-4 inline mr-2"/>The domain is not reachable from the browser. OBS Remote requires the Mac-side server/tunnel to be online; Clippedit requires its hosted deployment/custom domain to resolve.</div>}<div className="relative h-[700px] bg-black"><iframe key={`${frameKey}-${activeUrl}`} src={activeUrl} title={title} className="absolute inset-0 w-full h-full border-0" allow="camera; microphone; clipboard-read; clipboard-write; autoplay; fullscreen"/><div className="pointer-events-none absolute bottom-3 right-3 px-2 py-1 rounded-md bg-black/70 text-[10px] text-gray-500 border border-white/10">If embedding is blocked, use Open full app.</div></div></div>
}
function AgentStudio(){const leads=[['Content Lead','Scripts, clipping, repurposing, video pipeline, distribution'],['Trading Lead','Hybrid Journal, Guardian, review, risk/process'],['Business Lead','Affiliate Manager, Smart Life Brokers, Hybrid Funding, GHL growth'],['Systems Lead','GitHub, Mac workspace, MCP, deployments and reliability'],['Personal Lead','Calendar, family, health, Highest Self and life alignment']];return <div className="space-y-4"><div className="rounded-2xl border border-purple-500/20 bg-purple-950/20 p-5"><Bot className="w-5 h-5 text-purple-300 inline mr-2"/><span className="font-semibold text-white">Juno coordinates the creator team.</span><p className="text-sm text-gray-500 mt-2">Use the Live Agent Team tab for actual source-backed conversations and delegation.</p></div><div className="grid md:grid-cols-2 gap-3">{leads.map(([n,d])=><div key={n} className="rounded-xl border border-white/10 bg-white/[.03] p-4"><div className="font-semibold text-white">{n}</div><div className="text-xs text-gray-500 mt-1">{d}</div></div>)}</div></div>}
